openapi: 3.0.3
info:
  title: erp-aero
  version: 1.0.0
  description: erp-aero swagger
tags:
  - name: Auth
    description: ""
servers: [ { url: "http://localhost:3000/api" } ]

paths:
  # Authentication
  /auth/login:
    post:
      tags:
        - Auth
      requestBody:
        description: Sign in to the system
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        default:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          example: admin@admin.com
        password:
          type: string
          example: admin123

    LoginResponse:
      type: object
      properties:
        user:
          type: object
          properties:
            id:
              type: number
              example: 1
            email:
              type: string
              example: test@test.com
            firstName:
              type: string
              example: A
            lastName:
              type: string
              example: A
            status:
              type: string
              example: Active
        accessToken:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjYzMzA5MDQ5LCJleHAiOjE2NjMzMDk5NDl9.YHNQJKp_EQoMYUNXY87gGHTrf8jEhXQGcpUONSSMAok
        refreshToken:
          type: string
          example: 4a164bb1-a0fb-4ca0-9125-2724b9f85ba5

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
